drop table review;
drop table hotel;
drop table city;

create table city (
    id bigint generated by default as identity,
    country varchar(255) not null,
    map varchar(255) not null,
    name varchar(255) not null,
    state varchar(255) not null,
    primary key (id)
);

create table hotel (
    id bigint generated by default as identity,
    address varchar(255) not null,
    name varchar(255) not null,
    zip varchar(255) not null,
    city_id bigint not null,
    primary key (id)
);

create table review (
    id bigint generated by default as identity,
    check_in_date date not null,
    details varchar(5000) not null,
    idx integer not null,
    rating integer not null,
    title varchar(255) not null,
    trip_type integer not null,
    hotel_id bigint not null,
    primary key (id)
);